modLoader="javafml" #mandatory
loaderVersion="[2,)" #mandatory
license="GPLv2"
issueTrackerURL = "https://github.com/matthewperiut/Chisel-Reborn/issues"

[[mods]]
modId = "chisel"
version = "${version}"
displayName = "Chisel Reborn"
authors = ["Slaincow", "KnowYourKnot", "Original Creator: AUTOMATIC_MAIDEN"]
description = '''
Adds New Blocks!
'''
logoFile = "assets/chisel/icon.png"

[[mixins]]
config = "chisel.mixins.json"

[[dependencies.chisel]]
modId="minecraft"
type="required"
versionRange="[1.21.2,)"

[[dependencies.chisel]]
modId="neoforge"
type="required"
versionRange="[0,)"

[[dependencies.chisel]]
modId="architectury"
type="required"
versionRange="[0,)"